Name: Jane_Smith_example's assignment
Date/Time: 2023-03-30 01:53:39.679628

============================= test session starts =============================
platform win32 -- Python 3.10.5, pytest-7.1.3, pluggy-1.0.0 -- C:\Users\evan\AppData\Local\Programs\Python\Python310\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\evan\Desktop\Autograder\Autograder\To_Grade
collecting ... collected 2 items

test.py::test_module FAILED                                              [ 50%]
test.py::test_function PASSED                                            [100%]

================================== FAILURES ===================================
_________________________________ test_module _________________________________

    def test_module():
        dir_path = os.path.dirname(os.path.abspath(__file__))
        file_name =os.path.join(dir_path,f"{module_name}.py")
    
    
        expected_output = "expected_output.txt"
    
        result = subprocess.run(["python", file_name], stdout=subprocess.PIPE,stderr = subprocess.PIPE, text = True)
    
        with open(expected_output, "r") as f:
          expected = f.read()
>       assert result.stdout.strip() == expected.strip()
E       AssertionError: assert '1' == '1\n2\n3'
E         + 1
E         - 1
E         - 2
E         - 3

test.py:20: AssertionError
=========================== short test summary info ===========================
FAILED test.py::test_module - AssertionError: assert '1' == '1\n2\n3'
========================= 1 failed, 1 passed in 0.11s =========================
