Name: John_Smith_example's assignment
Date/Time: 2023-03-30 20:45:23.117917

============================= test session starts =============================
platform win32 -- Python 3.10.5, pytest-7.1.3, pluggy-1.0.0 -- C:\Users\evan\AppData\Local\Programs\Python\Python310\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\evan\Desktop\Autograder\Autograder
collecting ... collected 3 items

To_Grade/_test.py::test_module_output PASSED                             [ 33%]
To_Grade/_test.py::test_function_output PASSED                           [ 66%]
To_Grade/_test.py::test_function_return FAILED                           [100%]

================================== FAILURES ===================================
____________________________ test_function_return _____________________________

    def test_function_return():
    
    #ignore above ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    #assertions===========================================================================================================================================
      assert module.return_fun() == "Hello World"
    
      assert module.add_example(2,2) == 4
>     assert module.add_example(3,-3) == 0
E     assert -9 == 0
E      +  where -9 = <function add_example at 0x000001A8E2062170>(3, -3)
E      +    where <function add_example at 0x000001A8E2062170> = module.add_example

To_Grade\_test.py:61: AssertionError
=========================== short test summary info ===========================
FAILED To_Grade/_test.py::test_function_return - assert -9 == 0
========================= 1 failed, 2 passed in 0.12s =========================
